# Set this website's info
# Change "coffeebank" to your GitHub username
# Change "moonrise" to your repository name
url: "https://siegemc.net"
baseurl: "/"
siteIcon: https://cdn.discordapp.com/icons/626221022013816842/bc45d22c649c06e2453b7d8743a89459.png?size=192\
siteYear: 2020
siteFooterlink: https://siegerpg.net
showinSearchEngines: true
# googleAnalyticsID: (uncomment to use)


# Set basic server info
serverName: SiegeMC
serverDescription: An innovative dungeon-crawling MMORPG
serverIP: play.siegerpg.net

# Discord information
discordInvite: https://discord.siegerpg.net
discordServerID: 626221022013816842
discordChannelID: 626221024110837762


# Navbar Links at the top of the page
# Uncomment this section to add page functionality!
# siteNav:
#   - nname: Player Guide
#     nurl: guide
#   - nname: About
#     nurl: about


# Build settings
theme: minima
# plugins:
#   - jekyll-feed
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
